export const UserData = {
    SET_USER_DATA: "SET_USER_DATA",
    SET_TOKEN: "SET_TOKEN",
    SET_BANNER: 'SET_BANNER',
    SET_CATEGORIES_PSC_6: 'SET_CATEGORIES_PSC_6',
    SET_CATEGORIES_PSC: 'SET_CATEGORIES_PSC',
    SET_CATEGORIES_EAE: 'SET_CATEGORIES_EAE',
    SET_RECOMMENDED_COURSES: 'SET_RECOMMENDED_COURSES',
    SET_COUTINUE_YOUR_COURSE: 'SET_COUTINUE_YOUR_COURSE',
    SET_KEYWORD: 'SET_KEYWORD',
    SET_EAE_COURSESSCREEN_LIST: 'SET_EAE_COURSESSCREEN_LIST',
    SET_PSC_COURSESSCREEN_LIST: 'SET_PSC_COURSESSCREEN_LIST',
    SET_ARTICLE_LIST: 'SET_ARTICLE_LIST',
    SET_ARTICLE_CATEGORY: 'SET_ARTICLE_CATEGORY',
    SET_AUTHOR_LIST: 'SET_AUTHOR_LIST',
    SET_SAVE_GET_LIST: 'SET_SAVE_GET_LIST',
    SET_SAVE_CARTS: 'SET_SAVE_CARTS',
    SET_YOUTUBE: 'SET_YOUTUBE'
}