  require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'
platform :ios, '10.0'

target 'badabusiness' do
  config = use_native_modules!
  pod 'Firebase/Analytics'
  pod 'TOCropViewController', :git => 'https://github.com/TimOliver/TOCropViewController.git', :tag => '2.5.4'



  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'badabusinessTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
#  use_flipper!()
#
#  post_install do |installer|
#    react_native_post_install(installer)
#  end
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
  config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
  end
end
