import Constant from './Constant';
const AUTH_HEADER =
  'eyJpdiI6ImMzQkJzSStPc0tiS1lIXC9zWkRnZ3FRPT0iLCJ2YWx1ZSI6Imo1N0IwaytUellTblFMZjlsTU52cERGd0pHVlMyUzJGdms3ZW1XZmpueXM9IiwibWFjIjoiZDc0MzM5ZTYxYTI1ZTg0N2U0NDFiODc2NDYyZjMwYmMyNTAzNTUxMGNhYTg5MGRjZWJkZjlkZjhiYTU2OTExOSJ9';
export default {
  AUTH_HEADER: AUTH_HEADER,
  LOGIN_API: Constant.Base_Url + 'login',
  REGISTER_API: Constant.Base_Url + 'register',
  VERIFY_OTP_API: Constant.Base_Url + 'verify-otp',
  UPDATE_PROFILE: Constant.Base_Url + 'user/update',
  BANNER: Constant.Base_Url + 'banner',
  CATEGORY: Constant.Base_Url + 'category/',
  RECOMMENDED_COURSES: Constant.Base_Url + 'course/shorttermcourses',
  COUTINUE_YOUR_COURSE: Constant.Base_Url + 'course/shorttermcourses',
  KEYWORDS: Constant.Base_Url + 'search-keywords',
  Search: Constant.Base_Url + 'search',
  GET_CART_DETAILS: Constant.Base_Url + 'cart/list',
  ADD_CART: Constant.Base_Url + 'cart/add',
  CREATE_ORDER: Constant.Base_Url + 'order/create',
  EAELIST_COURSE_TAB: Constant.Base_Url + 'course/topics',
  PSC_COURSE_DETAIL: Constant.Base_Url + '/course/detail',
  Article_Categories: Constant.Base_Url + '/article/categories',
  Article_List: Constant.Base_Url + '/article/list',
  Article_Details: Constant.Base_Url + '/article/detail',
  GET_EAE_SCORE: Constant.Base_Url + 'credit/eae',
  GET_EAE_HISTORY: Constant.Base_Url + 'credit/eae-history',
  GET_PSE_SCORE: Constant.Base_Url + 'credit/psc',
  GET_PSC_HISTORY: Constant.Base_Url + 'credit/psc-history',
  GET_PSC_PAYMENT_DETAILS: Constant.Base_Url + 'payment/eae-data',
  DELETE_CART: Constant.Base_Url + 'cart/delete',
  AUTHOR_LIST: Constant.Base_Url + 'topic/author',
  GALLERY_LIST: Constant.Base_Url + 'gallery',
  EAE_TOPIC_DETAILS: Constant.Base_Url + 'topic/detail',
  SAVE_GET_LIST: Constant.Base_Url + 'course-topic/list',
  ADD_TO_SAVE: Constant.Base_Url + 'course-topic/add',
  DELETE_SAVE: Constant.Base_Url + 'course-topic/delete',
  USER_DETAILS: Constant.Base_Url + 'user',
  UPDATE_PROFILE_IMAGE: Constant.Base_Url + 'user/update-image',
  EAE_RATING_LIST: Constant.Base_Url + 'rate/topic-rating',
  PSC_RATING_LIST: Constant.Base_Url + 'rate/course-rating',
  ADD_RATING: Constant.Base_Url + 'rate/add',
  YOUTUBE: Constant.Base_Url + "youtube",
  YOUTUBE_SEARCH: Constant.Base_Url + "youtube/search",
  YOUTUBE_VIDEOS: Constant.Base_Url + "youtube/videos",
  ASSESSMENT_SUBMIT: Constant.Base_Url + 'topic/assessment',
};
