export default {
  intro2:
    'Bada Business के संस्थापक और CEO. मैं आपको अपना जीवन पूरी तरह से बदलने में मदद करूंगा.',
  drawerEditProfile: 'Edit Profile',
  drawer_Alladin_Ka_Chirag: 'Alladin Ka Chirag',
  drawer_Exclusive: 'Exclusive',
  drawer_Downloaded_Courses: 'Downloaded Courses',
  drawer_Catch_Us_At: 'Catch Us At',
  drawer_Subscription: 'Subscription',
  drawer_About_Bada_Business: 'About Us',
  drawer_How_to_Use: 'How to Use?',
  drawer_Help: 'Help',
  drawer_Rate_The_App: 'Rate The App',
  drawer_YouTube: 'YouTube',
  drawer_Articles: 'Articles',
  drawer_Live_Sessions: 'Live Sessions',
  drawer_Gallery: 'Gallery',
  drawer_Bada_Business: 'Bada Business',
  drawer_Dr_Vivek_Bindra: 'Dr. Vivek Bindra',
  drawer_Free_Learning: 'Free Learning',
  drawer_Speakers: 'Speakers',
  drawer_Guest_Speakers: ' Guest Speakers',
  drawer_language: 'Language',

  login_first_name: 'FIRST NAME',
  login_last_name: 'LAST NAME',

  bottom_Tab_Home: 'Home',
  bottom_Tab_Courses: 'Courses',
  bottom_Tab_Save: 'Saved',
  bottom_Tab_Chat: 'Chat',
  bottom_Tab_Account: 'Account',

  Search_Call_Search_for_courses: 'Search for courses',

  Home_Continue_with_your_course: 'Continue with your course',
  Home_Top_Categories: 'Top Categories',
  Home_Recommended_Courses: 'Recommended Courses',

  hiIm: 'Hi, I am',
  vivekBindra: 'VIVEK BINDRA',
  enterUrDetails: '“Enter your details',
  soWeCanKnow: 'so we can know each other better”',
  enterUrDetailAuth:
    'Please enter your details to authenticate your identity and allow you to use the app',
  uWillReceiveOtp:
    'You will receive an OTP for verification on your mobile number',
  fullName: 'Full Name',
  mobileNumber: 'Mobile Number',
  enterOTP: 'Enter OTP',
  enterDigitOTPReceive: 'Enter 4 digit OTP number received on',
  continue: 'Continue',
  whatWouldLikeToBecome: `What would you like\nto become?`,
  whatDescribeYouBest: `What describes you\nthe best?`,
  selectAnOptionWhichYouDream: `Select an option which you dream of\nyourself becoming in next 4-5 years.`,
  thisWillHelpUsToFetchCourse: `This will help us to fetch courses for\nyour knowledge.`,
  done: 'Done',
  skip: 'SKIP',
  lastTwoSteps: 'Last Two Steps',
  beAPartOfSuccessStory: 'Be a part of success story',
  otpWillExpire: 'OTP will expire in',
  Home_Modal_Keywords: 'Frequently Searched',
  Home_Categories: 'Categories',
  Home_Filter_By: 'FILTER BY',
  Home_PSC: 'PSC',
  Home_EAE: 'EAE',
  Home_How_to_use_Bada_Business: 'How to use Bada Business',
  Home_There_are_two_types_of_courses: 'There are two types of courses',
  Home_EAE_Everything_about_entrepreneurship:
    ' Everything About Entrepreneurship',
  Home_1_Credit_is_1_EAE_Course: '1 Credit is 1 EAE Course',
  Home_PSC_Problem_solving_courses: ' Problem Solving Courses',
  Home_1_EAE_course_provides_10PSC: '1 EAE course provides 10PSC',
  Home_Tip: 'Tip',
  Home_Purchase_life_time_membership_plan_in_order_to_access_Alladin_Ka_Chirag:
    ' Purchase life-time membership plan in order to access Alladin Ka Chirag',
  Home_My_Courses: 'My Courses',

  Sale_Subcategories: 'SUBCATEGORIES',
  Sale_View_All: 'VIEW ALL',
  Sale_Featured_Courses: 'Featured Courses',
  Sale_All_Courses: 'All Courses',
  Sale_Select_Subcategories: 'Select Subcategories',

  CoursesDetail_Overview: 'Overview',
  CoursesDetail_Related_Courses: 'Related Courses',
  CoursesDetail_Related_Courses: 'Related Courses',
  CoursesDetail_Ratings: 'Ratings',
  CoursesDetail_What_will_I_learn_from_this_course:
    'What will I learn from this course?',
  CoursesDetail_Syllabus: 'Syllabus',
  CoursesDetail_Extra_Learning: 'Extra Learning',
  CoursesDetail_View_All_Reviews: 'VIEW ALL REVIEWS',
  CoursesDetail_Write_A_Reviews: 'WRITE A REVIEWS',
  CoursesDetail_Write_A_Review: 'WRITE A REVIEW',
  CoursesDetail_Write_A_Reviews_Modal: 'Write a Reviews',
  CoursesDetail_Watch_Preview: 'Watch Preview',
  CoursesDetail_Assessment: 'Assessment',

  CoursesScreen_Checkout: 'Checkout',

  Courses_Select_Categories: 'Select Categories',

  Save_Saved_Courses: 'Saved Courses',

  Articles_Search_for_articles: 'Search for articles',
  Articles_Introduction: 'Introduction',
  editProfile: 'EDIT PROFILE',
  cart: 'Cart',
  savedCourse: 'SAVED COURSES',
  courses: 'Courses',
  proceedToCheckout: 'PROCEED TO CHECKOUT',
  inclusiveOfTaxes: `(Inclusive of Taxes)`,
  checkout: 'CHECKOUT',
  course: 'Course',
  priceSummery: 'PRICE SUMMERY',
  totalFee: 'Total Fee',
  grandFee: 'Grand Total',
  wouldYouLikeToClaim: 'Would you like to claim',
  gst: 'GST?',
  creditScore: 'Credit Score',
  pointSummeryDescription:
    'We will add 365 Credit points every year, out of which you can use 22 Credits per month to watch a video for EAE category course.',
  balanceCredit: 'Balance Credit',
  creditYear: '(Credits/Year)',
  lastAdded: 'LAST ADDED',
  creditOn: 'CREDITS ON',
  creditCarrieForward: 'Credits carried forwarded',
  recentTransaction: 'Recent Transaction',
  pscCourse: '(PSC Course)',
  total: 'Total',
  payNow: 'Pay Now',
  OrganizationName: 'ORGANISATION NAME',
  address: 'ADDRESS',
  gst: 'GST',
  Speakers_View_courses: 'VIEW COURSES',
  creditOn: 'CREDITS ON',
  creditCarrieForward: 'Credits carried forwarded',
  recentTransaction: 'Recent Transaction',
  pscCourse: '(PSC Course)',
  total: 'Total',
  payNow: 'Pay Now',
  OrganizationName: 'ORGANISATION NAME',
  address: 'ADDRESS',
  gst: 'GST',
  editProfileSmall: `Edit Profile`,
  FirstName: 'FIRST NAME',
  LastName: 'LAST NAME',
  EmailId: 'EMAIL ID',
  gender: 'GENDER',
  dob: 'DATE OF BIRTH',
  language: 'LANGUAGE',
  userLevel: 'USER LEVEL',
  currentIndustry: 'CURRENT INDUSTRY',
  wantToBecome: 'WANT TO BECOME',
  saveChanges: 'SAVE CHANGES',
  pleaseCommentYourReview: 'Please comment your review',
  reviews: 'reviews',
  Duration: 'Duration',
  NextVideos: 'Next Videos',

  Bestseller: 'BESTSELLER',
  pleaseEnterYourReview: 'Please enter your review',

  SelectLanguage: 'Select Language',
  iagreeWithTermandCon: 'By Clicking continue, I agree to',
  termAndcon: 'Terms & Condition',
  CAREGORIES: 'CAREGORIES',
  No_data_available: 'No data available',
  Speaker: 'Speaker',
  CourseDuration: 'Course Duration',
  NoofVideos: 'No. of Videos',
  Language_option_can_be_changed_anytime: 'Language option can be changed anytime.',
  Search_for_youtube_videos: 'Search for youtube videos',
};
