import {Platform, StyleSheet} from 'react-native';
import config from '../../config';
import {scale} from 'react-native-size-matters';

export default StyleSheet.create({
  innerContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'white',
    flexDirection: 'row',
    opacity: 1,
  },
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  subSingleCardTop: {
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop:Platform.OS=='ios'?0: 25,
    height: Platform.OS=='ios'?90: 120,
    paddingHorizontal: 20,
    flexDirection: 'row',
  },
  floatIcon: {
    position: 'absolute',
    bottom: 0,
    right: 10,
    width: config.Constant.SCREEN_WIDTH * 0.5,
    height: config.Constant.SCREEN_HEIGHT * 0.3,
  },
  introText: {
    fontFamily: config.Constant.Font_Regular,
    color: 'white',
    fontSize: scale(16),
    letterSpacing: 0.33,
  },
  lightText: {
    fontFamily: config.Constant.Font_Regular,
    color: config.Constant.COLOR_LIGHT_GREY,
    fontSize: scale(16),
    letterSpacing: 0.33,
    marginLeft: 10,
  },
  boldTxt: {
    fontFamily: config.Constant.Font_Bold,
    color: 'white',
    fontSize: scale(16),
    letterSpacing: 0.33,
    marginLeft: 10,
  },
  rowView: {
    //marginTop: 10,
    marginLeft: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    width: '55%',
  },
  btnStyle: {
    width: '90%',
    alignSelf: 'center',
    marginBottom: 5,
  },
  backIcon: {
    width: scale(15),
    height: scale(15),
    marginVertical: 20,
  },
  bodyHeader: {
    fontFamily: config.Constant.Font_Medium,
    color: config.Constant.COLOR_DARK_GREY,
    fontSize: scale(20),
    width: '90%',
    alignSelf: 'center',
    letterSpacing: 0.33,
    marginTop: scale(15),
    marginBottom: scale(3),
  },
  bodyHeaderLight: {
    fontFamily: config.Constant.Font_Regular,
    color: config.Constant.COLOR_DARK_GREY,
    opacity: 0.7,
    fontSize: scale(12),
    width: '90%',
    alignSelf: 'center',
    letterSpacing: 0.33,
    marginBottom: scale(30),
  },
  skipTxt: {
    fontFamily: config.Constant.Font_Medium,
    color: config.Constant.COLOR_BLUE,
    fontSize: scale(12),
    alignSelf: 'center',
    letterSpacing: 0.33,
    marginVertical: scale(10),
    marginHorizontal: scale(7),
  },
  txt: {
    fontFamily: config.Constant.Font_Medium,
    color: config.Constant.COLOR_DARK_GREY,
    fontSize: scale(12),
    letterSpacing: 0.33,
  },
  headerTitle: {
    fontFamily: config.Constant.Font_Medium,
    color: config.Constant.COLOR_WHITE,
    fontSize: scale(16),
    flex: 1,
    textAlign: 'left',
    letterSpacing: 0.33,
    marginLeft: 10,
  },
  body: {
    flex: 1,
    backgroundColor: 'white',
    borderTopRightRadius: 15,
    borderTopLeftRadius: 15,
    marginTop: -15,
  },
  textView1: {marginTop: 10, width: '90%', alignSelf: 'center'},
  textView2: {width: '90%', borderTopWidth: 0, alignSelf: 'center'},
  renderBox: {
    justifyContent: 'center',
    alignItems: 'flex-start',
    borderRadius: 10,
    borderWidth: 1.5,
    width: config.Constant.SCREEN_WIDTH * 0.425,
    marginBottom: config.Constant.SCREEN_WIDTH * 0.05,
    padding: 20,
    height: 110,
  },
  boxImage: {width: 40, height: 40, marginBottom: scale(10)},
  skipBtn: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 15,
  },
});
